version: '3'
services:
  nodeops:
    build: ./pm2-docker-alpine-master
    container_name: node-initproject
    hostname: 'node-initproject'
    networks:
      - initproject.net
    volumes:
     - ./:/app
    ports:
      - 3000:3000
#  mongo-3-4-4:
#    build: ./mongo-3-4-4
#    container_name: mongo-3-4-4-initproject
#    hostname: 'mongo-3-4-4-initproject'
#    volumes:
#     - /data/db:/data/db
#     - /var/lib/mongodb:/var/lib/mongodb
#    networks:
#      - initproject.net
networks:
  initproject.net:
    driver: bridge
