version: '3'
services:
  nodeops:
    build: ./app
    container_name: node-initproject
    hostname: 'node-initproject'
    networks:
    - initproject.net
    volumes:
    - ./app/src:/app/src
    ports:
    - 3000:3000
    depends_on:
    - mongodb
  mongodb:
    build: ./mongodb
    container_name: mongodb-initproject
    hostname: 'mongodb-initproject'
    volumes:
    - ./data/db:/data/db
    # - /var/lib/mongodb:/var/lib/mongodb
    networks:
    - initproject.net
    ports:
    - "27017:27017"
networks:
  initproject.net:
    driver: bridge
